
server:
  port: 8002

spring:
  jpa.hibernate:
    ddl-auto: update
  application:
    name: loan-service
  datasource:
    url: jdbc:mysql://localhost:3306/udemy
    driver-class-name:com:
      mysql:
        cj:
          jdbc:
            Driver: driver-class-name:com.mysql.cj.jdbc.Driver
    username: root
    password: root
  sql:
    init:
      mode: always
  jpa:
    show-sql: true


